kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: spring-cloud-consul-producer-2
  namespace: spring-cloud
  labels:
    app: spring-cloud-consul-producer-2
spec:
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: spring-cloud-consul-producer-2
    deploymentconfig: spring-cloud-consul-producer-2
  template:
    metadata:
      labels:
        app: spring-cloud-consul-producer-2
        deploymentconfig: spring-cloud-consul-producer-2
    spec:
      containers:
        - name: spring-cloud-consul-producer-2
          image: >-
            docker.io/sckehan/spring-cloud-consul-producer-2:latest
          ports:
            - containerPort: 8502
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always